import React from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { useSEO } from '../hooks/useSEO';
import { Link } from 'react-router-dom';

const HowTestingWorks = () => {
  const { t } = useLanguage();
  
  useSEO({
    title: t('seo.howTestingWorks.title', 'How Keyboard Testing Works — Browser Event Diagnostics'),
    description: t('seo.howTestingWorks.desc', 'Learn how browser KeyboardEvents translate physical key presses into observable data for diagnostic testing.'),
    url: 'https://keycheck.example.com/how-testing-works'
  });

  return (
    <main id="main-content" className="w-full max-w-4xl mx-auto px-4 py-12 animate-in fade-in duration-300">
      <header className="mb-12">
        <h1 className="text-4xl md:text-5xl font-black tracking-tighter uppercase mb-4">{t('footer.howTestingWorks', 'How Keyboard Testing Works')}</h1>
        <p className="text-xl text-muted-foreground">Understanding the mechanics of web-based key diagnostics.</p>
      </header>

      <section className="space-y-8 text-foreground/90 leading-relaxed">
        
        <div className="flex flex-col md:flex-row gap-6 items-start">
          <div className="w-12 h-12 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-2xl font-black shrink-0">1</div>
          <div>
            <h2 className="text-2xl font-bold uppercase tracking-wider mb-2">The Physical Press</h2>
            <p>
              When you press a key on your physical keyboard, the keyboard's internal microcontroller detects the electrical connection. It debounces the signal and sends a hardware scancode (like a USB HID usage code) over the wire to your computer's operating system.
            </p>
          </div>
        </div>

        <div className="flex flex-col md:flex-row gap-6 items-start">
          <div className="w-12 h-12 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-2xl font-black shrink-0">2</div>
          <div>
            <h2 className="text-2xl font-bold uppercase tracking-wider mb-2">OS Translation</h2>
            <p>
              Your Operating System (Windows, macOS, Linux) receives this scancode and translates it into a virtual key code based on your currently active OS keyboard layout (e.g., US QWERTY, French AZERTY). The OS then passes this event to the active application—in this case, your web browser.
            </p>
          </div>
        </div>

        <div className="flex flex-col md:flex-row gap-6 items-start">
          <div className="w-12 h-12 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-2xl font-black shrink-0">3</div>
          <div>
            <h2 className="text-2xl font-bold uppercase tracking-wider mb-2">Browser Events</h2>
            <p className="mb-4">
              The web browser wraps the OS event into a standard Javascript <code>KeyboardEvent</code>. It dispatches a <code>keydown</code> event when the key is pressed, and a <code>keyup</code> event when released.
            </p>
            <div className="bg-muted/50 p-4 rounded-lg border border-border">
              <p className="mb-2 font-bold text-sm uppercase tracking-wider">Crucial Event Properties:</p>
              <ul className="list-disc list-inside space-y-2 ml-2 text-sm">
                <li><code className="bg-background px-1 border border-border rounded font-mono">event.code</code>: Represents the physical location of the key on the board (e.g., <code>KeyQ</code>). This remains constant even if you switch your OS to an AZERTY layout.</li>
                <li><code className="bg-background px-1 border border-border rounded font-mono">event.key</code>: Represents the character generated by the press (e.g., <code>q</code> or <code>A</code> if Shift is held).</li>
                <li><code className="bg-background px-1 border border-border rounded font-mono">event.location</code>: Distinguishes between identical keys, like Left Shift (1) and Right Shift (2).</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="flex flex-col md:flex-row gap-6 items-start">
          <div className="w-12 h-12 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-2xl font-black shrink-0">4</div>
          <div>
            <h2 className="text-2xl font-bold uppercase tracking-wider mb-2">Diagnostic Logic</h2>
            <p>
              Our application listens globally for these <code>KeyboardEvent</code>s. By primarily using <code>event.code</code>, we map the input back to our visual on-screen keyboard layout, highlighting the exact physical key you pressed. By holding state between <code>keydown</code> and <code>keyup</code>, we can calculate active multi-key rollovers for our <Link to="/ghosting-test" className="text-primary hover:underline">Ghosting Test</Link>. You can view this raw data stream directly in our <Link to="/event-inspector" className="text-primary hover:underline">Event Inspector</Link>.
            </p>
          </div>
        </div>

      </section>
    </main>
  );
};

export default HowTestingWorks;
